# Continuous Testing on every PR.
name: CT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#
#               make        cmake
# cpu           openblas    Intel10_64ilp
# nvidia        mkl-int64   openblas
# amd           blis        mkl-int64
# intel         mkl         mkl
#
jobs:
  icl_lapackpp:
    timeout-minutes: 120
    strategy:
      matrix:
        maker:  [make, cmake]
        device: [cpu, gpu_nvidia, gpu_amd, gpu_intel]

        include:
            # Add `blas` and `blas_int` to existing configurations.
            - maker:    make
              device:   cpu
              blas:     openblas

            - maker:    cmake
              device:   cpu
              bla_vendor: Intel10_64ilp     # MKL int64 using CMake's FindBLAS

            - maker:    make
              device:   gpu_nvidia
              blas:     mkl
              blas_int: int64

            - maker:    cmake
              device:   gpu_nvidia
              blas:     openblas

            - maker:    make
              device:   gpu_amd
              blas:     blis

            - maker:    cmake
              device:   gpu_amd
              blas:     mkl
              blas_int: int64

            # For both make, cmake
            - device:   gpu_intel
              blas:     mkl

      fail-fast: false
    runs-on: ${{ matrix.device }}
    name: ${{matrix.maker}} ${{matrix.device}} ${{matrix.blas}}${{matrix.bla_vendor}}${{matrix.blas_libraries}} ${{matrix.blas_int}}

    # See variants.yml for use of some of these variables.
    env:
        maker:      ${{matrix.maker}}
        device:     ${{matrix.device}}
        check:      ${{matrix.check}}
        blas:       ${{matrix.blas}}
        blas_int:   ${{matrix.blas_int}}
        bla_vendor: ${{matrix.bla_vendor}}
        BLAS_LIBRARIES: ${{matrix.blas_libraries}}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: .github/workflows/configure.sh

      - name: Build
        run: .github/workflows/build.sh

      - name: Test
        run: .github/workflows/test.sh
